

// 3rd party resources
import React from 'react';
import './process.scss';
import Clock from 'react-live-clock';


function Process() {
  // returns new state from the reducers
  // const state = useSelector((state) => state.ProcessReducer);

  return (
    <div className="process">
      <div>
        <Clock className="clock" style={{opacity:'90%', color: 'red', borderRadius: '40%', background: 'black', fontSize: '70px'}} format={'HH:mm:ss'} ticking={true} timezone={'US/Pacific'} />
      </div>
      <div>
        <h1 className="sampleHeading" style={{position: 'center', opacity: '80%', background: 'black', color: 'green'}} >This is where the CRM APPlication will be at....................
        .............................
        ...1111111111111....
        ...........11..11...
        ...........11..11....
        ...........111111....
        ....................
        ...111111111111111.....
        ...11...........11..
        ...11...........11.......
        ...111111111111111.
        ...........................
        ...1111111111111111..
        ...11............11...........
        ...1111111111111111...........
        ....................
        </h1>
      </div>
    </div>
  );
}

export default Process;
